// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsConfig.Tests")>]
[<assembly: AssemblyProductAttribute("FsConfig")>]
[<assembly: AssemblyVersionAttribute("3.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-07-25T00:00:00.0000000+01:00")>]
[<assembly: AssemblyFileVersionAttribute("3.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("3.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","e818411f2c57f70fd8aac9cf66c1e6951220d261")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsConfig.Tests"
    let [<Literal>] AssemblyProduct = "FsConfig"
    let [<Literal>] AssemblyVersion = "3.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-07-25T00:00:00.0000000+01:00"
    let [<Literal>] AssemblyFileVersion = "3.1.0"
    let [<Literal>] AssemblyInformationalVersion = "3.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "e818411f2c57f70fd8aac9cf66c1e6951220d261"
