// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsConfig")>]
[<assembly: AssemblyProductAttribute("FsConfig")>]
[<assembly: AssemblyDescriptionAttribute("F# Libary for managing configuration data from environment variables and application config in a type-safe way")>]
[<assembly: AssemblyVersionAttribute("2.1.6")>]
[<assembly: AssemblyFileVersionAttribute("2.1.6")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsConfig"
    let [<Literal>] AssemblyProduct = "FsConfig"
    let [<Literal>] AssemblyDescription = "F# Libary for managing configuration data from environment variables and application config in a type-safe way"
    let [<Literal>] AssemblyVersion = "2.1.6"
    let [<Literal>] AssemblyFileVersion = "2.1.6"
    let [<Literal>] AssemblyConfiguration = "Release"
