// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsConfig")>]
[<assembly: AssemblyProductAttribute("FsConfig")>]
[<assembly: AssemblyVersionAttribute("4.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2023-06-18T00:00:00.0000000+01:00")>]
[<assembly: AssemblyFileVersionAttribute("4.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("4.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","247fcb0aa106a1934a3a151b6d2bfd716957f2a1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsConfig"
    let [<Literal>] AssemblyProduct = "FsConfig"
    let [<Literal>] AssemblyVersion = "4.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2023-06-18T00:00:00.0000000+01:00"
    let [<Literal>] AssemblyFileVersion = "4.0.0"
    let [<Literal>] AssemblyInformationalVersion = "4.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "247fcb0aa106a1934a3a151b6d2bfd716957f2a1"
